[Interface]
PrivateKey = uEM7FJeMdif7SXQhPV38EMKk6kS/Yh3L940pU+XekmQ=
Address = 10.2.2.2
DNS = 1.1.1.1

[Peer]
PublicKey = UkGPWBgjz+yHKPLZp5NZNr1H++cGr3r2enKc6xqDE3k=
Endpoint = 10.179.9.69:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
